### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by matthewdking** [facn2/90D#2]
- [x] create sign up view and route (1h)
- [x] taking user details and store in database (4h)
- [x] hash password (1h)
- [x] redirect to landing page (30m)
- [x] style (3h)
- [x] tests (1h)

**Comment by matthewdking** [comment]
Testing should be implemented as we go. Maybe this should be added to all user story issues and taken into account with the timing estimations.
