### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by matthewdking** [facn2/90D#3]
- [x] take email and check against database (4h)
- [x] check password with hashed password in database (2h)
- [x] redirect to landing page (1h)
- [x] style (1h)
- [x] testing (3h)
