### ISSUE TITLE
Add a new goal

### ISSUE THREAD

**Issue by matthewdking** [facn2/90D#4]
- [x] add new goal button and redirect new goal (1h)
- [x] create new view (4h)
- [x] user input added to database (6h)
- [x] redirect to goal viewing page (1h)
- [ ] style (3h)
- [ ] testing (4h)

**Comment by matthewdking** [comment]
Possible add new goal query
```JSON
db.users.update({
  _id: ObjectId("59b79b23fdd655b439cb06ad")
}, {
  $push: {
    goals: {
      sleep: {
        name: "sleep",
        dailyGoal: "all day",
        description: "less tired",
        reward: "feel better",
        endDate: "12/12/17"
      }
    }
  }
})
```
