### ISSUE TITLE
View more details about specific goals

### ISSUE THREAD

**Issue by matthewdking** [facn2/90D#6]
- [x] create view for goal details (2h)
- [x] click on specific goal and redirect to goal details (2h)
- [x] query the database and view specific details (4h)
- [ ] create charts (8h)
- [ ] style (3h)
