### ISSUE TITLE
Project skeleton

### ISSUE THREAD

**Issue by matthewdking** [facn2/90D#8]
- [x] set up express server #9 
- [x] handlebars #10 
- [x] folder structure #11 
- [x] pre-commit and linter #12 
- [x] database schema #16 
- [x] mongoDB setup #14 
- [x] initialise heroku project #13 
- [x] setup test structure #17 
- [x] setup travis #15

**Comment by matthewdking** [comment]
completed all tasks :white_check_mark:
